name: AetherShell CI/CD

on:
  push:
    tags:
      - "v*" # Trigger deployment only when you push a tag like v1.0

jobs:
  build-nds:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build NDS ROM
        run: |
          make clean
          make
      - name: Upload ROM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AetherShell-ROM
          path: "*.nds"

  build-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: "24"
          distribution: "temurin"
          cache: "maven"
      - name: Build Hub
        run: |
          cd hub
          mvn clean package -DskipTests
      - name: Upload Hub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AetherShell-Hub-Jar
          path: hub/target/hub.jar

  # THIS IS THE CD PART
  deploy-release:
    needs: [build-nds, build-hub]
    runs-on: ubuntu-latest
    steps:
      - name: Download NDS Artifact
        uses: actions/download-artifact@v4
        with:
          name: AetherShell-ROM

      - name: Download Hub Artifact
        uses: actions/download-artifact@v4
        with:
          name: AetherShell-Hub-Jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.nds
            hub.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
